apiVersion: apps/v1
kind: Deployment
metadata:
    name: gitops-nginx-deployment
    labels:
      app: gitops-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
          ports: 
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: gitops-nginx-service
    labels: 
        app: gitops-nginx
spec:
  type: ClusterIP
  selector:
    app: gitops-nginx
  ports:
    - port: 80
      targetPort: 80
